version: '3'

services:
  mysql:
    hostname: mysql
    container_name: jeepay-mysql
    # amd64 平台
    #image: mysql/mysql-server:latest
    image: mysql:8
    environment:
      LANG: C.UTF-8
      MYSQL_ROOT_PASSWORD: "rootroot"
      MYSQL_DATABASE: "jeepaydb"
      MYSQL_USER: "jeepay"
      MYSQL_PASSWORD: "jeepay"
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql
      - ./docs/sql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      jeepay:
        ipv4_address: 172.23.80.10
  activemq:
    build:
      context: ./docker/activemq
      dockerfile: Dockerfile
    hostname: activemq
    container_name: jeepay-activemq
    image: jeepay-activemq:latest
    ports: #- "1883:1883"
      #- "5672:5672"
      - "8161:8161"
      #- "61613:61613"
      #- "61614:61614"
      - "61616:61616"
    volumes:
      - activemq:/opt/activemq
      - ./docker/activemq/activemq.xml:/opt/activemq/conf/activemq.xml
    networks:
      jeepay:
        ipv4_address: 172.23.80.11
  redis:
    hostname: redis
    container_name: jeepay-redis
    image: redis:latest
    ports:
      - "6380:6379"
    networks:
      jeepay:
        ipv4_address: 172.23.80.12
    volumes:
      - redis:/data

networks:
  jeepay:
    ipam:
      config:
        - subnet: 172.23.80.0/24

volumes:
  mysql:
  redis:
  activemq:
#  rabbitmq: