server:
  port: 9217 #设置端口

spring:
  redis:
    database: 1    #1库：运营平台  #2库：商户系统 #3库：支付网关
  profiles:
    active: dev

qiDi:
  gateWay:
    url: https://api.sz9wang.com/api/v1
    secret-key: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczovL3R1eG0uYXJ0IiwidXNlcm5hbWUiOiJ0dXNkZXNpZ24ifQ.0SCNQBLp6_e3EEcQcT0Rqwp1QJ4AonY5eoOTiKMIkk0"

#系统业务参数
isys:
    jwt-secret: t7w3P8X6472qWc3u #生成jwt的秘钥。 要求每个系统有单独的秘钥管理机制。
